"""empty message

Revision ID: 0ce11cf7a9e5
Revises: c935bd389846
Create Date: 2023-03-30 14:58:29.658321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ce11cf7a9e5'
down_revision = 'c935bd389846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employed', sa.String(length=40), nullable=True))
        batch_op.drop_column('emplyed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emplyed', sa.VARCHAR(length=40), nullable=True))
        batch_op.drop_column('employed')

    # ### end Alembic commands ###
